import Head from "next/head";
import { Navbar } from "@/components/Navbar";
import { fetchData } from "@/services/http";

interface HomeProps {
  popularMovies?: any;
}

export default function Home(props: HomeProps): JSX.Element {
  console.log(props.popularMovies);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
}

export async function getStaticProps() {
  const popularMovies = await fetchData(
    `/movie/popular?api_key=${process.env.NEXT_PUBLIC_API_KEY}&language=en-US&page=1`
  );
  return { props: { popularMovies } };
}
